
%Programer: Fernando Contreras, 2021
%--------------------------------------------------------------------------
%Goals: this FUNCTION maneger the kind of pressure solver
%--------------------------------------------------------------------------
%Additional comments:
%--------------------------------------------------------------------------

function setmethod(kmap,wells,keywrite,invh,limiterflag,klb,elemsize,...
    bedgesize,inedgesize,auxpar,wellsc,velmedio,dmap,Dmedio,gamma,SS,...
    h_old,MM,dt,P)
%Define global parameters:
global phasekey pmethod numcase

%Get a preprocessment of pressure scheme (used in One-phase and Two-Phase).
if phasekey ~= 0
    %Call "preMPFA". This function calculate some important parameters to
    %be used in any PRESSURE solver.
    [transmvecleft,transmvecright,knownvecleft,knownvecright,storeinv,...
        Bleft,Bright,overedgecoord,normk,Fg,mapinv,maptransm,mapknownvec,...
        pointedge,bodyterm,Hesq,Kde,Kn,Kt,Ded,V,N,kmap,nflag,parameter,weightDMP,...
        nflagface,p_old,contnorm,weight,s,transmvecleftcon,transmvecrightcon,...
        knownvecleftcon,knownvecrightcon,storeinvcon,...
        Bleftcon,Brightcon,Fgcon,mapinvcon,maptransmcon,mapknownveccon,...
        pointedgecon, bodytermcon,Kdec,Knc,Ktc,Dedc,weightc,sc,weightDMPc,dparameter,...
        nflagnoc,nflagfacec,Con,lastimelevel,lastimeval,...
        gravrate,source] = preMPFA(kmap,klb,dmap,MM,h_old,wells);

end  %End of IF (execute "preMPFA")

%According "phasekey" the "One-phase" or "Two-phase" procedures are choose.
switch phasekey
    %One-Phase case:
    case 1 
        %Solve ONLY the PRESSURE equation chose the type of scheme 
        % according "pmethod"
        if strcmp(pmethod,'tpfa')
            %Get "pressure" and "flowrate"
            [pressure,flowrate,] = solvePressure_TPFA(transmvecleft,...
                knownvecleft,1,0,Fg,bodyterm);

            %MPFA-D (Gao and Wu, 2010)
        elseif strcmp(pmethod,'mpfad')
            %Get "pressure" and "flowrate"
            [pressure,flowrate,] = ferncodes_solverpressure(1,...
                wells,Hesq,Kde,Kn,Kt,Ded,nflag,weight,s,Con,Kdec,...
                Knc,Ktc,Dedc,nflagnoc,weightc,sc,SS,dt,h_old,MM,gravrate,P);
        elseif strcmp(pmethod,'mpfaql')
            [pressure,flowrate,]=ferncodes_solverpressureMPFAQL(nflag,...
                parameter,kmap,weightDMP,wells,1,V,1,N,weight,s);

        elseif strcmp(pmethod,'mpfah')
            [pressure,flowrate,]=ferncodes_solverpressureMPFAH(nflagface,...
                parameter,weightDMP,wells,SS,dt,h_old,MM,gravrate,P);
        elseif strcmp(pmethod,'nlfvpp')
            [pressure,flowrate,]=ferncodes_solverpressureNLFVPP(nflagno,...
                parameter,kmap,wells,1,V,1,N,p_old,contnorm);
        elseif strcmp(pmethod,'nlfvh')
            [pressure,flowrate,]=ferncodes_solverpressureNLFVH(nflagface,...
                parameter,kmap,wells,1,weightDMP,p_old,contnorm);
            %Any other Pressure solver (traditionals MPFA schemes)
        elseif strcmp(pmethod,'nlfvdmp')
            [pressure,flowrate,]=ferncodes_solverpressureDMP(nflagface,...
                parameter,wells,1,weightDMP,p_old,0,0,0);
        else
            %Get "pressure" and "flowrate"
            [pressure,flowrate,] = ...
                solvePressure(transmvecleft,transmvecright,knownvecleft,...
                knownvecright,storeinv,Bleft,Bright,wells,mapinv,maptransm,...
                mapknownvec,pointedge,1,bodyterm);
        end  %End of IF (type of pressure solver - one-phase flow)

        %Plot the fields (pressure, normal velocity, etc)
        %This function create the "*.vtk" file used in VISIT to
        %postprocessing the results
        postprocessor(pressure,flowrate,0,1,1,overedgecoord,1,keywrite,invh,normk);

        %It finishes the time counter and "profile".
        toc

        
    case 2 %Two-Phase flow case:
        %Initialize and preprocess the parameters:

        %Get the initial condition for the hyperbolic equation
        [Sw,lastimelevel,lastimeval] = applyinicialcond;

        %Define elements associated to INJECTOR and PRODUCER wells.
        [injecelem,producelem,satinbound,Sw,wells] = wellsparameter(wells,...
            Sw,klb);

        %Define flags and known saturation on the vertices and edges.
        [satonvertices,satonedges,flagknownvert,flagknownedge] = ...
            getsatandflag(satinbound,injecelem,Sw,nflagnoc,nflagfacec,0);

        %"preSaturation" - Preprocessor of the Saturation Equation
        [wvector,wmap,constraint,massweigmap,othervertexmap,lsw,swsequence,...
            ntriang,areatriang,prodwellbedg,prodwellinedg,mwmaprodelem,...
            vtxmaprodelem,coordmaprodelem,amountofneigvec,rtmd_storepos,...
            rtmd_storeleft,rtmd_storeright,isonbound] = ...
            preSaturation(flagknownedge,injecelem,producelem);

        %"IMPES" function. There, PRESSURE and SATURATION are solved.
        IMPES(Sw,injecelem,producelem,satinbound,wells,klb,satonvertices,...
            satonedges,flagknownvert,flagknownedge,wvector,wmap,constraint,...
            lsw,transmvecleft,transmvecright,knownvecleft,knownvecright,...
            mapinv,maptransm,mapknownvec,pointedge,storeinv,Bleft,Bright,...
            Fg,overedgecoord,bodyterm,normk,limiterflag,massweigmap,...
            othervertexmap,V,N,Hesq,Kde,Kn,Kt,Ded,kmap,nflag,swsequence,...
            ntriang,areatriang,lastimelevel,lastimeval,prodwellbedg,...
            prodwellinedg,mwmaprodelem,vtxmaprodelem,coordmaprodelem,...
            amountofneigvec,rtmd_storepos,rtmd_storeleft,rtmd_storeright,...
            isonbound,elemsize,bedgesize,inedgesize,parameter,...
            weightDMP,nflagface,p_old,contnorm,Kdec,Knc,Ktc,Dedc,weight,s,...
            Con,nflagnoc,weightc,sc,dparameter,SS,dt,h_old,MM,gravrate,...
            Dmedio,velmedio,nflagfacec,weightDMPc);
    case 3 % contaminant transport with pressure
        %          if numcase==243 || numcase==245 || numcase==247
        %              elem(:,5)=1;
        %          end

        %Define elements associated to INJECTOR and PRODUCER wells.
        [injecelem,producelem,satinbound,Con,wellsc] = wellsparameter(wellsc,...
            Con,klb);

        %Define flags and known concentration or saturation on the vertices and edges.
        [satonvertices,satonedges,flagknownvert,flagknownedge] = ...
            getsatandflag(satinbound,injecelem,Con,nflagnoc,nflagfacec,0);

        %"preSaturation" - Preprocessor of the concentration or saturation equation
        [wvector,wmap,constraint,massweigmap,othervertexmap,lsw,swsequence,...
            ntriang,areatriang,prodwellbedg,prodwellinedg,mwmaprodelem,...
            vtxmaprodelem,coordmaprodelem,amountofneigvec,rtmd_storepos,...
            rtmd_storeleft,rtmd_storeright,isonbound] = ...
            preSaturation(flagknownedge,injecelem,producelem);

        %"IMPEC" function. There, PRESSURE and CONCENTRATION are solved.
        IMPEC(Con,injecelem,producelem,satinbound,wells,klb,satonvertices,...
            satonedges,flagknownvert,flagknownedge,wvector,wmap,constraint,...
            lsw,transmvecleft,transmvecright,knownvecleft,knownvecright,...
            mapinv,maptransm,mapknownvec,pointedge,storeinv,Bleft,Bright,...
            Fg,overedgecoord,bodyterm,normk,limiterflag,massweigmap,...
            othervertexmap,V,N,Hesq,Kde,Kn,Kt,Ded,kmap,nflag,swsequence,...
            ntriang,areatriang,lastimelevel,lastimeval,prodwellbedg,...
            prodwellinedg,mwmaprodelem,vtxmaprodelem,coordmaprodelem,...
            amountofneigvec,rtmd_storepos,rtmd_storeleft,rtmd_storeright,...
            isonbound,elemsize,bedgesize,inedgesize,parameter,...
            weightDMP,nflagface,p_old,contnorm,dparameter,nflagnoc,...
            gamma,Dmedio,Kdec,Knc,Ktc,Dedc,weightc,sc,nflagfacec,...
            weightDMPc,wellsc,weight,s,velmedio,transmvecleftcon,transmvecrightcon,...
            knownvecleftcon,knownvecrightcon,storeinvcon,...
            Bleftcon,Brightcon,Fgcon,mapinvcon,maptransmcon,mapknownveccon,...
            pointedgecon, bodytermcon,gravrate);

    case 4 % hydraulic head simulation
        %% ===========================================================
        % steady-state problem
        if numcase==336 || numcase==334 ||numcase==335 || numcase==337 ...
                || numcase==338 || numcase==339 ||numcase==340 || ...
                numcase==341 || numcase==347 || numcase==341.1
            time=0;
            if strcmp(pmethod,'tpfa')
                %Get "pressure" and "flowrate"
                [pressure,flowrate,] = ferncodes_solvePressure_TPFA(Kde, Kn,...
                    nflagface, Hesq,0,0,0,0,0,0,SS,dt,h_old,MM,P,time,source);
                %MPFA-D (Gao and Wu, 2010)
            elseif strcmp(pmethod,'mpfad')
                %Get "pressure" and "flowrate"
                [pressure,flowrate,] = ferncodes_solverpressure(1,...
                    wells,Hesq,Kde,Kn,Kt,Ded,nflag,nflagface,weight,s,...
                    Con,Kdec,Knc,Ktc,Dedc,nflagnoc,weightc,sc,SS,dt,...
                    h_old,MM,gravrate,P,kmap,time,source);

            elseif strcmp(pmethod,'mpfaql')
                [pressure,flowrate,]=ferncodes_solverpressureMPFAQL(nflag,...
                    parameter,kmap,weightDMP,wells,1,V,1,N,weight,s);

            elseif strcmp(pmethod,'mpfah')
                [pressure,flowrate,]=ferncodes_solverpressureMPFAH(nflagface,...
                    parameter,weightDMP,wells,SS,dt,h_old,MM,gravrate,1,P,time,source);
            elseif strcmp(pmethod,'nlfvpp')
                [pressure,flowrate,]=ferncodes_solverpressureNLFVPP(nflagno,...
                    parameter,kmap,wells,1,V,1,N,p_old,contnorm,source);
            elseif strcmp(pmethod,'nlfvh')
                [pressure,flowrate,]=ferncodes_solverpressureNLFVH(nflagface,...
                    parameter,kmap,wells,1,weightDMP,p_old,contnorm);
                %Any other Pressure solver (traditionals MPFA schemes)
            elseif strcmp(pmethod,'nlfvdmp')
                [pressure,flowrate,]=ferncodes_solverpressureDMP(nflagface,...
                    parameter,wells,1,weightDMP,p_old,0,0,0);
            else
                %Get "pressure" and "flowrate"
                [pressure,flowrate,] = ...
                    solvePressure(transmvecleft,transmvecright,knownvecleft,...
                    knownvecright,storeinv,Bleft,Bright,wells,mapinv,maptransm,...
                    mapknownvec,pointedge,1,bodyterm,P);
            end  %End of IF (type of pressure solver - one-phase flow)

            %Plot the fields (pressure, normal velocity, etc)
            %This function create the "*.vtk" file used in VISIT to
            %postprocessing the results
            postprocessor(pressure,flowrate,0,1,1,overedgecoord,1,keywrite,...
                invh,normk,0);
            if numcase==333
                plotandwrite(0,0,pressure,0,0,0,0,0,overedgecoord);
            end

            %Mesage for the user:
            disp('------------------------------------------------');
            disp('>> Global hydraulic head extrema values:');
            max_conval = max(pressure)
            min_conval = min(pressure)

        else
            %% ===============================================================
            % transient-state problem
            hydraulic(wells,overedgecoord,V,N,Hesq,Kde,Kn,Kt,Ded,kmap,nflag,...
                parameter,h_old,contnorm,SS,MM,weight,s,dt,gravrate,nflagface,...
                weightDMP,P);
        end
        
    case 5 % contaminant transport with hydarulic head

        %          if numcase==243 || numcase==245 || numcase==247
        %              elem(:,5)=1;
        %          end
        tempo=0;
        %Define elements associated to INJECTOR and PRODUCER wells.
        [injecelem,producelem,satinbound,Con,wellsc] = wellsparameter(wellsc,...
            Con,klb);

        %Define flags and known concentration or saturation on the vertices and edges.
        [satonvertices,satonedges,flagknownvert,flagknownedge] = ...
            getsatandflag(satinbound,injecelem,Con,nflagnoc,nflagfacec,0);

        %"precsaturation" - Preprocessor of the concentration or saturation equation
        [wvector,wmap,constraint,massweigmap,othervertexmap,lsw,swsequence,...
            ntriang,areatriang,prodwellbedg,prodwellinedg,mwmaprodelem,...
            vtxmaprodelem,coordmaprodelem,amountofneigvec,rtmd_storepos,...
            rtmd_storeleft,rtmd_storeright,isonbound] = ...
            preSaturation(flagknownedge,injecelem,producelem);

        %"IMHEC" function. There, HYDRAULIC HEAD and CONCENTRATION are solved.
        IMHEC(Con,injecelem,producelem,satinbound,wells,klb,satonvertices,...
            satonedges,flagknownvert,flagknownedge,wvector,wmap,constraint,...
            lsw,transmvecleft,transmvecright,knownvecleft,knownvecright,...
            mapinv,maptransm,mapknownvec,pointedge,storeinv,Bleft,Bright,...
            Fg,overedgecoord,bodyterm,normk,limiterflag,massweigmap,...
            othervertexmap,V,N,Hesq,Kde,Kn,Kt,Ded,kmap,nflag,swsequence,...
            ntriang,areatriang,lastimelevel,lastimeval,prodwellbedg,...
            prodwellinedg,mwmaprodelem,vtxmaprodelem,coordmaprodelem,...
            amountofneigvec,rtmd_storepos,rtmd_storeleft,rtmd_storeright,...
            isonbound,elemsize,bedgesize,inedgesize,parameter,...
            weightDMP,nflagface,p_old,contnorm,dparameter,nflagnoc,...
            gamma,Dmedio,Kdec,Knc,Ktc,Dedc,weightc,sc,nflagfacec,...
            weightDMPc,wellsc,weight,s,velmedio,transmvecleftcon,transmvecrightcon,...
            knownvecleftcon,knownvecrightcon,storeinvcon,...
            Bleftcon,Brightcon,Fgcon,mapinvcon,maptransmcon,mapknownveccon,...
            pointedgecon, bodytermcon,gravrate,SS,MM,P,tempo);

        
    otherwise %It Solves only the HYPERBOLIC Equation:

        %Get the initial condition for the hyperbolic equation
        [Sw,lastimelevel,lastimeval] = applyinicialcond;

        %Define flags and known variables on the edges.
        [satonedges,flagknownedge] = hyperb_getknownval;

        %Preprocessor of the Saturation Equation
        [wvector,wmap,constraint,massweigmap,othervertexmap,lsw,swsequence,...
            ntriang,areatriang,prodwellbedg,prodwellinedg,mwmaprodelem,...
            vtxmaprodelem,coordmaprodelem,amountofneigvec,rtmd_storepos,...
            rtmd_storeleft,rtmd_storeright,isonbound] = ...
            preSaturation(flagknownedge,0,0);

        %"hyperb_getflowrate" calculate the flow rate for the hyperbolic
        %equation.
        [flowrate,v] = hyperb_getflowrate;

        %"hyperb_transient" is a function equivalent to "IMPES"
        hyperb_transient(Sw,satonedges,flagknownedge,wvector,wmap,...
            limiterflag,massweigmap,othervertexmap,flowrate,v,constraint,...
            lsw,keywrite,invh,swsequence,ntriang,areatriang,lastimelevel,...
            lastimeval,elemsize,bedgesize,inedgesize,amountofneigvec);

end  %End of SWITCH


end
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%FUNCTION
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------

% Function "parametersauxiliary"
function[Hesq,Kdec,Knc,Ktc,Dedc,wightc,sc,weightDMPc,nflag,dparameter ]=...
    parametersauxiliary(dmap,N,lastimeval)
global pmethod
dparameter=0;
Hesq=0;
Kdec=0;
Knc=0;
Ktc=0; Dedc=0;
% calculate the parameters for the dispersive flux
if strcmp(pmethod,'nlfvpp')
    %temos usado para muitos estes o seguinte rutina
    [dparameter,]=ferncodes_coefficient(dmap);
    % calculate inpertolation weigts
    [wightc,sc] = ferncodes_Pre_LPEW_2_con(dmap,N);
    weightDMPc=0;
    % adequação dos flags de contorno
    nflag = logical(lastimeval~=0)*ferncodes_calflag(lastimeval)+...
        logical(lastimeval==0)*nflag;
elseif strcmp(pmethod,'mpfaql')
    %temos usado para muitos estes o seguinte rutina
    [dparameter,]=ferncodes_coefficient(dmap);
    [weightDMPc]=ferncodes_weightnlfvDMP(dmap);
    % calculate inpertolation weigts

    [wightc,sc] = ferncodes_Pre_LPEW_2_con(dmap,N);
elseif strcmp(pmethod,'mpfah')
    %temos usado para muitos estes o seguinte rutina
    [dparameter,]=ferncodes_coefficient(dmap);
    [weightDMPc]=ferncodes_weightnlfvDMP(dmap);
    wightc=0;sc=0;
elseif strcmp(pmethod,'mpfad')
    %Get preprocessed terms:
    [Hesq,Kdec,Knc,Ktc,Dedc] = ferncodes_Kde_Ded_Kt_Kn(dmap);
    % calculate inpertolation weigts
    weightDMPc=0;
    [wightc,sc] = ferncodes_Pre_LPEW_2_con(dmap,N);

    % adequação dos flags de contorno
    nflag = logical(lastimeval~=0)*ferncodes_calflag(lastimeval)+...
        logical(lastimeval==0)*nflag;
elseif strcmp(pmethod,'tpfa')
    %[transmvecleftc,knownvecleftc,] = transmTPFA(dmap,0);
    [Hesq,Kdec,Knc,Ktc,Dedc] = ferncodes_Kde_Ded_Kt_Kn(dmap);
    wightc=0;sc=0;weightDMPc=0;
end
end

